### ISSUE TITLE
Test color laser printer

### ISSUE THREAD

**Issue by bladow-bros** [bladow-bros/BROS-IT#7]
Determine if the color laser printer is in working order and if so, what steps need to be taken to make it usable by BROS Staff.

**Comment by ghost** [comment]
Printer is in working order. It will need to be connected to the network via ethernet cable in order to configure it so it can be used on WIFI. Below is the link for the printer's manual.

http://h10032.www1.hp.com/ctg/Manual/c02776822.pdf

**Comment by Hachi05** [comment]
used the current awesome bros laptop (windows 7, black laptop, used to be chuck jrs) to install the software/configure the printer. got it connected to wifi -- assigned static ip of 192.168.1.5 (does not overlap with DHCP)

previously I had tried configuring software using my (unsupported) windows 10 laptop
