### ISSUE TITLE
Tech Rodeo Requirements

### ISSUE THREAD

**Issue by bladow-bros** [bladow-bros/BROS-IT#8]
Determine if the Theater Tech team has specific IT (hardware or software) requirements at the upcoming (April 30) meetup. This will help us plan for device purchases.

**Comment by Hachi05** [comment]
we had no requirements that needed fulfilling ahead of time.

we used the projector above the stage (vga for windows, vga -> mdp for mac) with personal laptops and the current awesome bros laptop (black laptop, used to be chuck jrs).
